"""make_icons.py -- the app logo for every platform, from one drawing.

The logo is the Android launcher's (android/res/drawable/ic_launcher_fg.xml):
two folders side by side, orange and blue, with a white copy arrow -- the
dual-panel idea -- on the dark rounded square of android/res/values/colors.xml
(icon_bg). It is drawn here from the same coordinates (a 108-unit canvas) at
8x size and scaled down, so every size is smooth.

Writes (commit the results; builds never need Python):
  icons/mmcfm.ico            Windows: 16..256 px, embedded in the exe (icons/mmcfm.rc)
  icons/mmcfm.icns           macOS: the .app's icon
  icons/mmcfm.png            Linux / FreeBSD: 256 px, next to the .desktop file
  icons/favicon.png          web: 64 px
  android/res/mipmap-*/ic_launcher.png   Android before 8.0 (no adaptive icons)
  src/flogo.h                32 and 64 px ARGB pixels: the window and tray icon at run time

Run: python tools/make_icons.py   (needs Pillow)
"""
import os
from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SS = 8                       # supersampling
BG = (0x1B, 0x22, 0x30, 255)

FOLDERS = [
    # (x offset, back colour, front colour)
    (0, (0xD9, 0x98, 0x2A, 255), (0xF2, 0xB5, 0x3C, 255)),
    (32, (0x3A, 0x6F, 0xD8, 255), (0x4F, 0x8C, 0xFF, 255)),
]


def logo(size, square=True, crop=(14, 94)):
    """The logo at size px. square: the dark rounded square behind (desktop
    icons); crop: the part of the 108-unit canvas that fills the icon."""
    big = size * SS
    lo, hi = crop
    k = big / (hi - lo)

    def P(x, y):
        return ((x - lo) * k, (y - lo) * k)

    img = Image.new('RGBA', (big, big), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    if square:
        m = big * 0.06
        d.rounded_rectangle((m, m, big - m, big - m), radius=big * 0.2, fill=BG)
    r = 3 * k
    for dx, back, front in FOLDERS:
        # back: the body with the tab on its left (M27,38 h11 l4,4 h7 ... rounded 3)
        x0, x1 = P(24 + dx, 0)[0], P(52 + dx, 0)[0]
        d.rounded_rectangle((x0, P(0, 41)[1], x1, P(0, 72)[1]), radius=r, fill=back)
        d.polygon([P(24 + dx, 42), P(24 + dx, 41), P(27 + dx, 38), P(38 + dx, 38), P(42 + dx, 42)], fill=back)
        d.pieslice((P(24 + dx, 38)[0], P(0, 38)[1], P(30 + dx, 0)[0], P(0, 44)[1]), 180, 270, fill=back)
        # front: M24,47 h28 v22 a3,3 rounded bottom
        d.rounded_rectangle((x0, P(0, 47)[1], x1, P(0, 72)[1]), radius=r, fill=front,
                            corners=(False, False, True, True))
    # the copy arrow: M44,57 h14 v-4 l7,6 l-7,6 v-4 h-14 z
    d.polygon([P(44, 57), P(58, 57), P(58, 53), P(65, 59), P(58, 65), P(58, 61), P(44, 61)],
              fill=(255, 255, 255, 255))
    return img.resize((size, size), Image.LANCZOS)


def write_c_header(path, sizes):
    out = ['/* flogo.h -- the app logo as pixels (generated by tools/make_icons.py; do not edit).',
           '** 0xAARRGGBB, rows top to bottom, not premultiplied. */',
           '#ifndef FLOGO_H', '#define FLOGO_H', '']
    for s in sizes:
        px = logo(s).load()
        out.append('static const unsigned int kLogo%d[%d * %d] = {' % (s, s, s))
        row = []
        for y in range(s):
            for x in range(s):
                r, g, b, a = px[x, y]
                row.append('0x%08X' % ((a << 24) | (r << 16) | (g << 8) | b))
                if len(row) == 8:
                    out.append('  ' + ', '.join(row) + ',')
                    row = []
        if row:
            out.append('  ' + ', '.join(row) + ',')
        out.append('};')
        out.append('')
    out.append('#endif')
    open(path, 'w', newline='\n').write('\n'.join(out) + '\n')


def main():
    icons = os.path.join(ROOT, 'icons')
    os.makedirs(icons, exist_ok=True)
    big = logo(1024)
    sizes = [16, 20, 24, 32, 40, 48, 64, 96, 128, 256]
    logo(256).save(os.path.join(icons, 'mmcfm.ico'), sizes=[(s, s) for s in sizes],
                   append_images=[logo(s) for s in sizes[:-1]])
    big.save(os.path.join(icons, 'mmcfm.icns'))
    logo(256).save(os.path.join(icons, 'mmcfm.png'))
    logo(64).save(os.path.join(icons, 'favicon.png'))
    # Android before 8.0: the same square icon per density
    for dens, s in (('mdpi', 48), ('hdpi', 72), ('xhdpi', 96), ('xxhdpi', 144), ('xxxhdpi', 192)):
        d = os.path.join(ROOT, 'android', 'res', 'mipmap-' + dens)
        os.makedirs(d, exist_ok=True)
        logo(s).save(os.path.join(d, 'ic_launcher.png'))
    write_c_header(os.path.join(ROOT, 'src', 'flogo.h'), [32, 64])
    rc = os.path.join(icons, 'mmcfm.rc')
    open(rc, 'w', newline='\n').write('// The exe\'s icon (build.sh compiles this with zig rc).\n1 ICON "mmcfm.ico"\n')
    print('written: icons/, android/res/mipmap-*/ic_launcher.png, src/flogo.h')


if __name__ == '__main__':
    main()
