/* fsdl.h -- SDL2, linked or loaded at run time.
**
** Include this instead of <SDL.h>. With FM_SDL_DYNAMIC (tcc, Linux, macOS,
** BSD) every SDL_* call listed in fsdl_list.h goes through a function
** pointer that fsdl_load() fills from the SDL2 shared library; otherwise the
** calls are plain static links (Windows/zig, Android, web).
**
** Design decisions:
**   - The redirects (#define SDL_Foo fmsdl_SDL_Foo) are generated by build.sh
**     from fsdl_list.h into build/gen/gen_sdl_redef.h, because the C
**     preprocessor cannot emit #define lines from an X-macro.
**   - SDL_main is not used on desktop (SDL_MAIN_HANDLED); Android needs it,
**     since SDLActivity calls SDL_main in libmain.so.
*/
#ifndef FSDL_H
#define FSDL_H

#if !defined(__ANDROID__) && !defined(SDL_MAIN_HANDLED)
#  define SDL_MAIN_HANDLED
#endif

#include "SDL.h"

#ifdef FM_SDL_DYNAMIC
#  define FM_SDL_FN(ret, name, params) extern ret (SDLCALL *fmsdl_##name) params;
#  include "fsdl_list.h"
#  undef FM_SDL_FN
#  include "gen_sdl_redef.h"
#endif

/* Use instead of SDL_CreateThread (which is a macro on Windows). */
SDL_Thread *fm_thread_create(SDL_ThreadFunction fn, const char *name, void *data);

/* Loads SDL2 (dynamic builds); always true for static builds. On failure
** `err` holds a message for the user. */
int fsdl_load(char *err, int cap);
void fsdl_unload(void);

#endif
